import esbuild from 'esbuild';
import process from 'process';
import { readFile, writeFile } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { builtinModules } from 'node:module';

// Node's own list of built-in module names — replaces the third-party
// `builtin-modules` package (flagged by Obsidian's plugin review for using
// a module that has a native equivalent). We also emit the `node:`-prefixed
// aliases so esbuild externalizes e.g. both `path` and `node:path`.
const builtins = [...builtinModules, ...builtinModules.map((m) => `node:${m}`)];

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Kanban Pro — Local-first Kanban / PM for Obsidian
*/
`;

const prod = (process.argv[2] === 'production');

/**
 * CSS pipeline.
 *
 * Obsidian serves a single `styles.css` from the plugin root. The vault
 * plugin directory typically only has `manifest.json`, `main.js` and
 * `styles.css` symlinked in — anything else under `src/` is NOT
 * available at runtime. So `@import url('./src/styles/*.css')` from the
 * root stylesheet 404s at load time and none of our `kp-*` rules apply.
 *
 * Fix: concatenate the per-feature stylesheets under `src/styles/` into
 * the root `styles.css` at build time, in the order documented in
 * `src/styles/_order` (mirrored below). The order matters — tokens.css
 * defines `--kp-*` custom properties consumed by every other sheet, and
 * mobile.css / a11y.css must come last to win cascade.
 */
const CSS_ORDER = [
  'tokens.css',
  'shell.css',
  'board.css',
  'lane.css',
  'card.css',
  'rail.css',
  'editor.css',
  'views.css',
  'paywall.css',
  'banners.css',
  'dashboard.css',
  'tracking.css',
  'templates.css',
  'recoveryDiff.css',
  'settings.css',
  'onboarding.css',
  'mobile.css',
  'a11y.css',
];

async function bundleStyles() {
  const stylesDir = path.join(__dirname, 'src', 'styles');
  const outPath = path.join(__dirname, 'styles.css');
  const header = [
    '/* ============================================================',
    '   Kanban Pro — bundled stylesheet (generated by esbuild.config.mjs)',
    '   Source files live under src/styles/. Edit those, not this file.',
    '   ============================================================ */',
    '',
  ].join('\n');
  const chunks = [header];
  for (const name of CSS_ORDER) {
    const filePath = path.join(stylesDir, name);
    const css = await readFile(filePath, 'utf8');
    chunks.push(`/* ===== src/styles/${name} ===== */`);
    chunks.push(css.trimEnd());
    chunks.push('');
  }
  await writeFile(outPath, chunks.join('\n'), 'utf8');
}

await bundleStyles();

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  jsx: 'automatic',
  plugins: [
    {
      // Watch-mode rebuilds re-bundle the CSS too. Errors are surfaced
      // through esbuild's standard error pipeline so `npm run dev`
      // shows them in the terminal.
      name: 'kanban-pro-css',
      setup(build) {
        build.onStart(async () => {
          try {
            await bundleStyles();
          } catch (err) {
            return {
              errors: [{
                text: `CSS bundle failed: ${err instanceof Error ? err.message : String(err)}`,
              }],
            };
          }
          return null;
        });
      },
    },
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
